# ---------------------------------------------------------------------------
# Sprint 5 - Ansible Inventory
#
# The control node manages BOTH servers in the [servers] group.
# ---------------------------------------------------------------------------

[servers]
linux1 ansible_host=172.31.26.210 ansible_connection=local
linux2 ansible_host=172.31.26.22 ansible_user=ubuntu
[servers:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
